// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yadmwidoofzidzcgdtoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZG13aWRvb2Z6aWR6Y2dkdG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDY2NjAsImV4cCI6MjA1MTY4MjY2MH0.QQESbST4ij3X7sZSK05gHkkCaU_M_ZTLP94tPCcmBWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);